name: Main workflow

on:
  push:
    branches: [main]

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          token: ${{secrets.GIT_TOKEN}}
      - name: Set local git settings
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          git config --local user.signingkey "${{ secrets.GIT_GPG }}"
          git config --local commit.gpgsign true
          git remote set-url origin "https://github.com/$GITHUB_REPOSITORY"
      - name: Bump and publish
        run: |
          yarn release
          git push --follow-tags origin main

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      - name: Set image tag
        id: tag
        run: |
          echo "::set-output name=bare::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}"
          echo "::set-output name=semver::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.package.outputs.version }}"
          echo "::set-output name=latest::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest"
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ steps.tag.outputs.latest }} -t ${{ steps.tag.outputs.semver }} .
      - name: Push docker image
        run: docker push ${{ steps.tag.outputs.bare }} --all-tags
