name: Build

on:
  push:
    branches: [main]

jobs:
  beatrice-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: build:install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: yarn build
